### ISSUE TITLE
Unuseful antiaffinity group for some kind of groups

### ISSUE THREAD

**Issue by davepanarese** [entercloudsuite/terraform-modules#4]
Leave forced antiaffinity group for critical services like database, proxy, cache, elasticsearch and container service manager.
Create variable for other services and set disable by default.

**Comment by jsecchiero** [comment]
Hi Davide!
thanks for the issue!
Indeed an option for enable/disable anti-affinity is useful here but i disagree that the default pattern must be disabled because the user 90% of times try to creates HA services and not vice versa.
Please use real world examples where you are trying to do non-HA services or else where standalone services are limited because of anti-affinity.
Jacopo

**Comment by jsecchiero** [comment]
Close for inactivity
